/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.form_Template;

import SingletonClass.LstChiTietDoUong_singleton;
import static Test.ComponentImageCapture.getScreenShot;
import com.view.component.paneOfmenu;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.ChiTietDoUong;

/**
 *
 * @author 84374
 */
public class GenMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form GenMenuFrame
     */
    private ArrayList<paneOfmenu> lstPaneMenu = new ArrayList<>();
    private ArrayList<ChiTietDoUong> lstChiTietDoUong = new ArrayList<>();

    public GenMenuFrame() {
        initComponents();
        panelMenuDisplay.setLayout(new BorderLayout());
        loadFirstAppear();
        this.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuDisplay = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelMenuDisplay.setBorder(new javax.swing.border.MatteBorder(null));
        panelMenuDisplay.setOpaque(false);

        javax.swing.GroupLayout panelMenuDisplayLayout = new javax.swing.GroupLayout(panelMenuDisplay);
        panelMenuDisplay.setLayout(panelMenuDisplayLayout);
        panelMenuDisplayLayout.setHorizontalGroup(
            panelMenuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        panelMenuDisplayLayout.setVerticalGroup(
            panelMenuDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jButton3.setText("In Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenuDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenuDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        saveScreenShot(panelMenuDisplay);
    }//GEN-LAST:event_jButton3ActionPerformed

    public void loadFirstAppear() {
        lstChiTietDoUong = LstChiTietDoUong_singleton.getInstance().lstChiTietDoUongs;
        paneOfmenu paneMenu = new paneOfmenu(lstChiTietDoUong, null);
        paneMenu.setPreferredSize(new Dimension(541, 550));
        lstPaneMenu.add(paneMenu);
        setForm(lstPaneMenu.get(0));
    }

    public void next() {

    }

    public void pre() {

    }

    private void setForm(JComponent com) {
        panelMenuDisplay.removeAll();
        panelMenuDisplay.add(com);
        panelMenuDisplay.repaint();
        panelMenuDisplay.revalidate();
    }

    public static BufferedImage getScreenShot(
            Component component) {
        BufferedImage image = new BufferedImage(
                640, 630,
                BufferedImage.TYPE_INT_RGB
        );
        // call the Component's paint method, using
        // the Graphics object of the image.
        component.paint(image.getGraphics()); // alternately use .printAll(..)
        return image;
    }

    public void saveScreenShot(Component f) {
        BufferedImage img = getScreenShot(
                f);
        JOptionPane.showMessageDialog(
                null,
                new JLabel(
                        new ImageIcon(
                                img.getScaledInstance(
                                        img.getWidth(null) / 2,
                                        img.getHeight(null) / 2,
                                        Image.SCALE_SMOOTH)
                        )));
        try {
            // write the image as a PNG
            ImageIO.write(
                    img,
                    "png",
                    new File("screenshot.png"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GenMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GenMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GenMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GenMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GenMenuFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel panelMenuDisplay;
    // End of variables declaration//GEN-END:variables
}
